### ISSUE TITLE
Liste des matchs du jour

### ISSUE THREAD

**Issue by jerlachavan** [XCarrel/Volscore#12]
Nous voudrions avoir une méthode permettant de récupérer les matchs triés du plus ancien au plus récent ainsi que toutes les colonnes pour pouvoir choisir ce que nous afficherons en fonction des maquettes.

**Comment by XCarrel** [comment]
Ce besoin me semble être couvert par la méthode getGamesByTime.
Si c'est le cas : fermez cette issue
Sinon, veuillez me donner des précisions sur ce qui manque
