### ISSUE TITLE
Snippet n'affiche pas le 0

### ISSUE THREAD

**Issue by joaberch** [XCarrel/Volscore#6]
Lorsque j'active le Snippet et que je tape des nombres tels que '0' ou '01' le '0' ne s'affiche pas, néanmoins si je tape '10' le '0' s'affiche.

**Comment by XCarrel** [comment]
Bonjour,
J'ai corrigé le snippet dans le repo.
Faites git pull et reprenez le code de la fonction.

Xavier Carrel

De : joaberch ***@***.***>
Envoyé : lundi, 6 février 2023 10:11
À : XCarrel/Volscore ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [XCarrel/Volscore] Snippet n'affiche pas le 0 (Issue #6)


Lorsque j'active le Snippet et que je tape des nombres tels que '0' ou '01' le '0' ne s'affiche pas, néanmoins si je tape '10' le '0' s'affiche.

-
