### ISSUE TITLE
Une méthode getLastMatchs

### ISSUE THREAD

**Issue by ederiazl** [XCarrel/Volscore#7]
Il s'agit d'une méthode pour récupérer les 5 derniers matchs joués.

**Comment by XCarrel** [comment]
J'ai ajouté la méthode `getMatchByTime()` .
Elle vous permet de récupérer les matchs dans le passé. A vous de voir comment l'utiliser pour avoir seulement les 5 dernier matches.
Voir la documentation doxygen de ce repo pour les détails.
